# travis yaml file for python

notifications:
    email: false
language: python
python:
  - "3.6"
services:
  - postgresql
# command to install dependencies
install:
        #- pip install -r requirements.txt
  - pip3 install psycopg2
# command to run tests
script:
  - pytest -v
